name: neurohome
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  webview_flutter: ^4.4.2
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  process_run: ^0.13.0+2
  universal_io: ^2.2.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  dart_jsonwebtoken: ^3.0.1
  # bcrypt removido - no es necesario con JWT

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/nodejs/